"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const classes_1 = require("./classes");
exports.default = () => {
    const pub = new classes_1.Publisher();
    const sub1 = new classes_1.Subscriber("Bruno");
    const sub2 = new classes_1.Subscriber("Pedro");
    const sub3 = new classes_1.Subscriber("Daniel");
    const sub4 = new classes_1.Subscriber("Frederico");
    const sub5 = new classes_1.Subscriber("Diego");
    pub.subscribe(sub1);
    pub.subscribe(sub2);
    pub.subscribe(sub3);
    pub.subscribe(sub4);
    pub.subscribe(sub5);
    pub.notifyAll();
    console.log("\n Removing Daniel \n");
    pub.unsubscribe(sub3);
    pub.notifyAll();
};
